language: node_js
node_js:
  - 7
os:
  - linux
  - centos
  - macosx
  - windows
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-3.0.4.tgz -O /tmp/mongodb.tgz
  - tar -xvf /tmp/mongodb.tgz
  - mkdir /tmp/data
  - ${PWD}/mongodb-linux-x86_64-3.0.4/bin/mongod --dbpath /tmp/data  &
  - until nc -z localhost 27017; do echo Waiting for MongoDB; sleep 1; done
  - sleep 3
script:
  - npm run mocha && npm run ng test -- --single-run && npm run lint && npm run ng lint
sudo: false
env:
  global:
  - NODE_ENV=e2e
# addons:
#   sauce_connect: true
